[WIP]initial commit for v1.25 release notes
DaoCloud-OpenSource/docs pull request #9
Opened 2022-08-11 14:50 UTC by pacoxu

2022-08-12 09:13 UTC, pacoxu commented on kubernetes/sig-release/v1.25/release.md
> +
sig apps: job 支持退出码

2022-08-18 06:44 UTC, calvin0327 commented on kubernetes/sig-release/v1.25/release.md
> +新版本包含 40 个 enhancements「1.24 版本 46 个、1.24 版本 45 个」其中 13 个功能升级为稳定版，10 个已有功能进行优化，另有多达 15 个全新功能以及2个废弃的功能。
```
「1.24 版本 46 个、1.24 版本 45 个」
```
这个好像有点问题

2022-08-18 06:44 UTC, calvin0327 commented on kubernetes/sig-release/v1.25/release.md
> +- 增加 DisruptionTarget 容器组 condtion 来表明 Pod 停止原因
```suggestion
- 增加 DisruptionTarget 容器组 condtion 来表明 Pod 停止原因
```

typo：`condtion` =>  `Condition`

2022-08-18 06:44 UTC, calvin0327 commented on kubernetes/sig-release/v1.25/release.md
> +- seccomp 和 AppArmor 支持升级到 Beta 并默认启用。
seccomp => Seccomp ?

2022-08-18 07:03 UTC, mengjiao-liu requested changes

2022-08-18 07:03 UTC, mengjiao-liu commented on kubernetes/sig-release/v1.25/release.md
> +- apiserver 废弃了  `--service-account-api-audiences` ，可以使用 `--api-audiences` 替代。
```suggestion
- apiserver 废弃了  `--service-account-api-audiences`，可以使用 `--api-audiences` 替代。
```

2022-08-18 07:03 UTC, mengjiao-liu commented on kubernetes/sig-release/v1.25/release.md
> +- kubeadm 中，功能门 UnversionedKubeletConfigMap GA，这意味着新版本中 kubeadm 只会读取 kube-system 命名空间下名为 kubelet-config的 configmap，在 UnversionedKubeletConfigMap 开启之前，kubeadm 使用的是 `kubelet-config-x.yy` x.yy 是当前 Kuber
```suggestion
- kubeadm 中，功能门 UnversionedKubeletConfigMap GA，这意味着新版本中 kubeadm 只会读取 kube-system 命名空间下名为 kubelet-config 的 configmap，在 UnversionedKubeletConfigMap 开启之前，kubeadm 使用的是 `kubelet-config-x.yy` x.yy 是当前 Kubernetes 版本。如果集群当中目前没有 kubelet-config 的 configmap，集群管理员需要在升级之前手动复制 `kubeelt-config-x.yy` configmap 的内容来创建名为 kubelet-config 的 configmap。
```

2022-08-18 07:03 UTC, mengjiao-liu commented on kubernetes/sig-release/v1.25/release.md
> +该功能在 pod.Spec 引入了新字段 hostUsers 允许用户开启或者关闭容器组的用户命名空间。目前该功能的开发才进展到第一个阶段，目前只有 pod 不使用存储卷，或者只使用以下类型的存储（configmap、secret、downwardAPI、emptyDir、projected）的情况下，才能够启用该功能。在未来的版本中，该功能将会完全开放，并且将会支持所有的存储类型。
```suggestion
该功能在 pod.Spec 引入了新字段 hostUsers 允许用户开启或者关闭容器组的用户命名空间。目前该功能的开发才进展到第一个阶段，目前只有 Pod 不使用存储卷，或者只使用以下类型的存储（configmap、secret、downwardAPI、emptyDir、projected）的情况下，才能够启用该功能。在未来的版本中，该功能将会完全开放，并且将会支持所有的存储类型。
```
pod 首字母大写，我看下文是大写的，最好保持统一

2022-08-18 07:50 UTC, pacoxu commented on kubernetes/sig-release/v1.25/release.md
> +对于 VPA 来说，第一阶段的代码已经合并，目前在 CRI 层面支持了对 Pod 资源限制和资源预留进行修改。VPA 在未来版本中，将会完善自动的弹性规则和设置方法。 VPA 的使用场景会和 HPA 横向弹性伸缩有所不同，HPA 可以通过改变容器组数量来适应资源需求的变化和请求的压力变化。而 VPA 则是通过改变容器组的资源限制来适应资源需求的变化和请求的压力变化。VPA 的优势在于，这些操作无
In-Place Update of Pod Resources 目前的名字，我感觉应该吧 VPA 放在最后简单说一下 就可以了。vpa 设计 好像不同地方不太一样。

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/2010320/185340206-8ec3a2b9-4b57-44a9-be82-f8fa08f2b83f.png">

总体来看 request 和 limit 好像都会被修改，而且会按照一定的超配比例 就是 limit/request 按照一定的比例进行扩缩。 我再改改

2022-08-18 07:53 UTC, pacoxu commented on kubernetes/sig-release/v1.25/release.md
> +对于 VPA 来说，第一阶段的代码已经合并，目前在 CRI 层面支持了对 Pod 资源限制和资源预留进行修改。VPA 在未来版本中，将会完善自动的弹性规则和设置方法。 VPA 的使用场景会和 HPA 横向弹性伸缩有所不同，HPA 可以通过改变容器组数量来适应资源需求的变化和请求的压力变化。而 VPA 则是通过改变容器组的资源限制来适应资源需求的变化和请求的压力变化。VPA 的优势在于，这些操作无
https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/1287-in-place-update-pod-resources

2022-08-22 03:17 UTC, kerthcet commented on kubernetes/sig-release/v1.25/release.md
> +- Add `NodeInclusionPolicy` to `TopologySpreadConstraints` in PodSpec.
这个和 `Introduce NodeInclusionPolicies to specify nodeAffinity/nodeTaint strategy when calculating pod topology spread skew.` 冲突. 一个就好了。

2022-08-22 03:17 UTC, kerthcet commented on kubernetes/sig-release/v1.25/release.md
> +- [Beta] Add configurable grace period to probes  (default false but already beat in v1.22; default to true in v1.25)
s/beat/Beta/ or `already true`

2022-08-22 03:17 UTC, kerthcet commented on kubernetes/sig-release/v1.25/release.md
> +本次发布中， DaoCloud 重点贡献了 sig-node 和 sig-scheduling 相关内容，具体功能点如下：
Also add kubeadm?

2022-08-22 03:17 UTC, kerthcet commented on kubernetes/sig-release/v1.25/release.md
> +- kubelet 为 OpenTelemetry Tracing 提供了初步支持。
Scheduling KEP: https://github.com/kubernetes/enhancements/pull/3244

2022-08-22 08:11 UTC, wzshiming commented on kubernetes/sig-release/v1.25/release.md
> +太平洋时间 2022 年 8 月 23 日，Kubernetes 1.25 正式发布。此版本更新距离上版本发布时隔 4 个月，是 2022 年的第二个版本。受新冠疫情和国际形势变化影响以及发布团队的全球化性质，发布过程也经历了非常大的挑战。
```suggestion
太平洋时间 2022 年 8 月 23 日，Kubernetes 1.25 正式发布。此版本距离上版本发布时隔 4 个月，是 2022 年的第二个版本。受新冠疫情和国际形势变化影响以及发布团队的全球化性质，发布过程也经历了非常大的挑战。
```

2022-08-22 08:13 UTC, wzshiming commented on kubernetes/sig-release/v1.25/release.md
> +本版本包含了多个安全相关的功能，比如用户命名空间的支持、SELinux 挂载容器组的优化、CSI NodeExpansion 支持 Secrets 等。除此之外，为了提高集群管理员和应用管理员的体验，Job 增加了不重试选项，密钥管理服务 KMS 发布了 v2 版本，临时容器共 GA， kubelet 支持获取容器组的检查点，这两个公都可以更好地帮助用户进行事故排查和分析。相关的重要功能会在下一
> 临时容器共 GA 

> 这两个公都可以更好地帮助用户进行事故排查和分析

语句不通

2022-08-22 08:22 UTC, wzshiming commented on kubernetes/sig-release/v1.25/release.md
> +此外， DaoCloud 还参与了十多个问题修复，在 v1.25 发布过程中总计贡献 53 个提交，详情请见[贡献列表](https://www.stackalytics.io/cncf?project_type=cncf-group&release=all&metric=commits&module=github.com/kubernetes/kubernetes&date=118)（该版本的
```suggestion
此外， DaoCloud 还参与了十多个问题修复，在 v1.25 发布过程中总计贡献 53 个提交，详情请见[贡献列表](https://www.stackalytics.io/cncf?project_type=cncf-group&release=all&metric=commits&module=github.com/kubernetes/kubernetes&date=118)（该版本的两百多位贡献者中有来自 DaoCloud 的 11 位）。也正是因为「DaoCloud 道客」在 Kubernetes 社区的持续贡献，殷纳成为了 SIG Scheduling 小组的 Reviewer ，殷纳同时也是 Kueue 项目的核心贡献者， Kueue 是一个基于 Kubernetes 原生的作业队列和弹性配额管理器。此外，SIG Node Reviewer 张世明的个人项目[fake-kubelet](https://github.com/wzshiming/fake-kubelet) 转入 Kubernetes 组织，也就是目前的 [KWOK](https://github.com/kubernetes-sigs/kwok/) （Kube-WithOut-Kubelet） 项目。该项目旨在以最低的成本模拟大量的 Kubelet，从而模拟大量节点和载荷，服务于各种控制面组件测试。
```

2022-08-22 14:21 UTC, pacoxu commented on kubernetes/sig-release/v1.25/release.md
> +- Add `NodeInclusionPolicy` to `TopologySpreadConstraints` in PodSpec.
Removed.

2022-08-22 14:30 UTC, pacoxu commented on kubernetes/sig-release/v1.25/release.md
> +- kubelet 为 OpenTelemetry Tracing 提供了初步支持。
这个可以这么翻译么

- 调度功能：在滚动更新的时候，PodTopologySpread 调度策略依然能够起作用。

2022-08-22 14:32 UTC, pacoxu commented on kubernetes/sig-release/v1.25/release.md
> +本版本包含了多个安全相关的功能，比如用户命名空间的支持、SELinux 挂载容器组的优化、CSI NodeExpansion 支持 Secrets 等。除此之外，为了提高集群管理员和应用管理员的体验，Job 增加了不重试选项，密钥管理服务 KMS 发布了 v2 版本，临时容器共 GA， kubelet 支持获取容器组的检查点，这两个公都可以更好地帮助用户进行事故排查和分析。相关的重要功能会在下一
临时容器 GA

这两个功能都可以更好地帮助用户进行事故排查和分析

2022-08-23 02:01 UTC, kerthcet commented on kubernetes/sig-release/v1.25/release.md
> +- kubelet 为 OpenTelemetry Tracing 提供了初步支持。
Pod 滚动更新时，由于调度器无法区分新老 Pod，导致拓扑调度策略不生效，现在可以通过开启 `MatchLabelKeysInPodTopologySpread` 功能门，完善该策略。

2022-08-23 02:12 UTC, pacoxu commented on kubernetes/sig-release/v1.25/release.md
> +- kubelet 为 OpenTelemetry Tracing 提供了初步支持。
Updated.

2022-08-23 07:36 UTC, merged